### ISSUE TITLE
【邀请】诚挚邀请您参与博客通用标准制定

### ISSUE THREAD

**Issue by MYXXTS** [caibingcheng/rssblog#21]
尊敬的rssblog：

您好！岁末年终，首先提前祝贵处成员新年快乐。

我处是[BlogStandards](https://github.com/BlogStandards)，诚邀您参与编订[《General Blog Tag Standard （通用博客标签准则）》](https://github.com/BlogStandards/GBTS)以及[General Blog Post Tag Standard （通用博客标签准则）](https://github.com/BlogStandards/GBPTS)。基于对贵组织的了解，我处认为在与贵处的合作中也定能对双方在相关领域的发展中大有裨益。为使贵处对该标准有初步了解，下附简介。

关于预期目标：该标准以规范博客程序聚合输出为主体目的，规范组织博客收录、组织博文推荐、博客博文聚合输出为基础目标，以达到令访客能够快捷寻找目标博客和文章的效果，制定一种通用的博客、博文等相关规范。

若贵处对该标准的制定有所兴趣或建议，诚挚期待您的回复！

BlogStandards
2023年1月13日

**Comment by caibingcheng** [comment]
> 尊敬的rssblog：
> 
> 
> 
> 您好！岁末年终，首先提前祝贵处成员新年快乐。
> 
> 
> 
> 我处是[BlogStandards](https://github.com/BlogStandards)，诚邀您参与编订[《General Blog Tag Standard （通用博客标签准则）》](https://github.com/BlogStandards/GBTS)以及[General Blog Post Tag Standard （通用博客标签准则）](https://github.com/BlogStandards/GBPTS)。基于对贵组织的了解，我处认为在与贵处的合作中也定能对双方在相关领域的发展中大有裨益。为使贵处对该标准有初步了解，下附简介。
> 
> 
> 
> 关于预期目标：该标准以规范博客程序聚合输出为主体目的，规范组织博客收录、组织博文推荐、博客博文聚合输出为基础目标，以达到令访客能够快捷寻找目标博客和文章的效果，制定一种通用的博客、博文等相关规范。
> 
> 
> 
> 若贵处对该标准的制定有所兴趣或建议，诚挚期待您的回复！
> 
> 
> 
> BlogStandards
> 
> 2023年1月13日

抱歉，过了很久才回复😞 我暂不考虑参与此次标准的制定，因为目前的兴趣点和关注点不在此处。

祝你们顺利！💪
