### ISSUE TITLE
谢谢创建了一个新的博客聚合平台。看到一直是 5 位博客 ， 所以来问问以后会慢慢扩充吗？

### ISSUE THREAD

**Issue by AboutRSS** [caibingcheng/rssblog#4]
如题。我已将其加到我的 ALL-about-RSS list 里了，加油。

**Comment by caibingcheng** [comment]
Hi, 还会扩充的, 但是更新频率会比较慢. (更新来源主要是我看过的一些博客或者自荐, 一般都是个人自建站)
