### ISSUE TITLE
github.com/saveweb/rss-list 来“偷”源了

### ISSUE THREAD

**Issue by yzqzss** [caibingcheng/rssblog#6]
我们是另一个博客列表“**独立博客&播客全订阅”**（主要在Telegram上活动： https://t.me/s/blogrsslist ），将您的博客列表中的那10个member也去重收录到了我们的列表中。
特此通知，希望得到“饶恕”。:-D

**Comment by caibingcheng** [comment]
> 我们是另一个博客列表“**独立博客&播客全订阅”**（主要在Telegram上活动： https://t.me/s/blogrsslist ），将您的博客列表中的那10个member也去重收录到了我们的列表中。
> 特此通知，希望得到“饶恕”。:-D

感谢~~
